export const MAX_QUESTION_LENGTH = 1000;
export const MAX_ANSWER_LENGTH = 1000;

export const RATE_LIMIT_MAX_ATTEMPTS_DEFAULT = 5;
export const RATE_LIMIT_WINDOW_SECONDS_DEFAULT = 60;

export const AUTO_BAN_THRESHOLD_DEFAULT = 5;
export const AUTO_BAN_WINDOW_DEFAULT = 3600;
